require("core.plugin_config.harpoon")
require("core.plugin_config.lsp")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.telescope")
require("core.plugin_config.theme")
require("core.plugin_config.treesitter")
require("core.plugin_config.undotree")
require("core.plugin_config.vim-fugitive")

